version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: compras-postgres-docker
    environment:
      POSTGRES_DB: sistema_compras
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123-abc
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: compras-backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sistema_compras
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123-abc

volumes:
  postgres_data:
